# -*- coding: utf-8 -*-
"""Variables .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4Eaaj9G8DzBD4M8q0Nh3ifvsyJOW5_K

https://www.youtube.com/watch?v=TqPzwenhMj0&list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3&index=6

# **Variables in python**
"""

2+3

5+8

1+1

x=2
x+3

y=3
x+y

x=9
x+y

z=x+y
z

z

x+10

name='youtube'
name

hello=name + 'rocks'
hello

hello

hello[0]

hello[6]

hello[-1]

hello[-2]

hello[0:2]

hello[1:4]

hello[2:6]

hello[1:]

hello[:3]

hello[:-3]

hello

hello[3:10]

hello[3:100]

"""# **Strings in Python are immutable**"""

hello[0:3]='my'

"""The error TypeError: 'str' object does not support item assignment occurs because strings in Python are immutable. This means you cannot change individual characters or slices of an existing string.

To achieve a similar result, you need to create a new string by concatenating the desired parts. Here's how you can replace the first three characters of the hello string:
"""

hello[0]='R'

'my'+hello[3:6]

hello

'yaswanth'+ hello[0:10]

hello

hello[0:5]='test'

'test'+hello

len(hello)

len(hello)

"""https://www.youtube.com/watch?v=_OZIAHg5i7M&list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3&index=13

# **More on variables**

# **#9 Python Tutorial for Beginners | More on Variables in Python**
"""

num=5
num

num1=10
num1

hen=num+num1
hen

id(num)

id(num1)

id2='yaswanth'
id2

id(id2)

a=10
b=a
b

a

b

id(a)

id(b)







































































































































